[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidx-activityCompose = "1.12.3"
androidx-appcompat = "1.7.1"
androidx-core-ktx = "1.17.0"
androidx-espresso-core = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-test-junit = "1.3.0"

compose-plugin = "1.10.0"
compose-navigation = "2.9.1"
compose-viewmodel = "2.9.6"

dataframe = "1.0.0-Beta4"

junit = "4.13.2"

koalaplot = "0.10.4"

koin = "4.1.1"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
ksp-version = "2.3.5"

material3 = "1.9.0"
material-icons = "1.7.3"

room = "2.8.4"

serialization = "1.10.0"
sqlite = "2.6.2"
sqlite-jdbc = "3.51.1.0"



[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

compose-uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-plugin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-plugin" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-plugin" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-plugin" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-plugin" }
compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-plugin" }

compose-desktop-linuxX64={module="org.jetbrains.compose.desktop:desktop-jvm-linux-x64", version.ref="compose-plugin"}
compose-desktop-macosX64={module="org.jetbrains.compose.desktop:desktop-jvm-macos-x64", version.ref="compose-plugin"}
compose-desktop-macosArm64={module="org.jetbrains.compose.desktop:desktop-jvm-macos-arm64", version.ref="compose-plugin"}
compose-desktop-winX64={module="org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref="compose-plugin"}

compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }

dataframe-jdbc = { module = "org.jetbrains.kotlinx:dataframe-jdbc", version.ref = "dataframe" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }

koalaplot = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplot" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-jvm = { module = "io.insert-koin:koin-compose-jvm", version.ref = "koin" }

kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }

material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-gradleplugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }

sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
